version: '3.8'

services:
  # Container for the recommendation server
  recommendation-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: recommendation_engine
    command: ["./recommend_app", "5000"]
    ports:
      - "5000:5000"

  # Container for running Python tests
  python-tests:
    image: python:3.10-slim
    # We depend on the recommendation server - tests won't run until the server is up
    depends_on:
      - recommendation-server
    # Map the current directory to the container's app directory
    volumes:
      - .:/app
    working_dir: /app/Recommendation/tests
    # run the tests using unittest
    command: ["python", "-m", "unittest", "test_tcp_client.py"]
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=recommendation-server
  
  # Container for DB
  mongodb:
    image: mongo:latest
    container_name: food_db
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db 
  
  # Container for the api server
  api:
    build: ./web-server
    container_name: node_api
    ports:
      - "3000:3000" 
    depends_on:
      - mongodb
      - recommendation-server
    environment:
      - MONGO_URI=mongodb://mongodb:27017/food_delivery_db
      - TCP_HOST=recommendation-server
      - TCP_PORT=5000
      - JWT_SECRET=my_super_secret_key_12345

volumes:
  mongo_data: